### ISSUE TITLE
!st2session list is not helpful on user IDs

### ISSUE THREAD

**Issue by nicholasamorim** [nzlosh/err-stackstorm#33]
running

`!st2session list` on slack returns:

```
Sessions: errbot%serviceUserID: errbot%service, Is Sealed: False, SessionID: e88cde80-5c27-49d1-893b-df5ae7ddb2a3, Creation Date: 2020-08-04 08:10:47, Modified Date: 2020-08-04 08:10:47, Expiry Date: 2020-08-07 08:10:47

U53LN2TGCUserID: U43LB1TGC, Is Sealed: False, SessionID: 8db8dafd-ca97-4237-a0b6-cf16acfaf80d, Creation Date: 2020-08-06 11:19:49, Modified Date: 2020-08-06 11:19:49, Expiry Date: 2020-08-09 11:19:49
```

IS there any way we can add the actual nickname or username to it? It's a bit of a digging to figure out people's IDs. Sure, there's actually a way to figure out on Slack, but I wonder if there's any technical impediment to this.

**Comment by nzlosh** [comment]
Slack has 4 user attributes, the ID which is persistent and immutable.  The fullname, the display name and the username are modifiable by the user.  The User ID is used to ensure a unique identifier maps to the session id otherwise users could have their sessions hijacked.

```
│ person   │ `@Carlos`   │
├──────────┼─────────────┤
│ nick     │ `nzlosh`    │
├──────────┼─────────────┤
│ fullname │ `Carlos`    │
├──────────┼─────────────┤
│ client   │ `DL6ER0NPP` │
```
Which of these 4 attributes do you think would be most useful to add to the session information?

**Comment by nicholasamorim** [comment]
I think the `person` one is the most useful ones because

a) you can configure errbot using it: `ACL_FRONTEND_TEAM = ["@nicholas", "@carlos"]`
b) typing it on slack itself shows the (possible) persons without having to press enter or anything like that.

That said, not sure what `nick` means in Slack context.

**Comment by nzlosh** [comment]
I tend to agree, the `person` attribute would be the most well known.  I'll include it as part of the session output. Errbot's `nick` attribute is what Slack calls `username`.

**Comment by nzlosh** [comment]
You can upgrade to version 2.1.4 for improved detail in the session list on Slack.
