### ISSUE TITLE
command with two equals

### ISSUE THREAD

**Issue by nzlosh** [nzlosh/err-stackstorm#37]
Reference: https://github.com/errbotio/errbot/issues/1517

**Comment by nzlosh** [comment]
@minifygb can you share the action-alias definition that is being called?

**Comment by Niyakiy** [comment]
@nzlosh here is the action-alias code:
can you suggest what we're possibly missing? or it is a bug.

```---
name: composer_licensing
pack: zd_chatops
description: "Action aliases for Composer Licensing interface"
action_ref: "zd_chatops.composer_licensing"
formats:
  - display: "licensing (request) [options]"
    representation:
      - "licensing {{request=help}}"
ack:
  format: "Composer Licensing is processing your request..."
  append_url: false
result:
  format: "Composer Licensing execution result: {% if execution.result.tasks[1].state == 'succeeded' %}Success{% else %}Failure{% endif %}{{execution.result.tasks[1].result.stdout}}"
  extra:
    slack:
      color: "{% if execution.result.tasks[1].state == 'succeeded' %}good{% else %}danger{% endif %}"

**Comment by nzlosh** [comment]
StackStorm action-aliases can take arbitrary key/value pairs at the end of the representation string.  This provides for a lot of flexibility but complicates parsing (which is done using regular expressions).  My gut feeling is the trailing `111==` is being interpreted by StackStorm as a key value pair `"111" = "="`.

I'll try to replicate the issue on my setup to get a better idea.  If it's not on the StackStorm side, then it'll most likely be a bug in err-stackstorm not handling the action-alias definition correctly.

**Comment by Niyakiy** [comment]
we've spotted such behavior in all cases when any request ended by two eq signs (`==`). One of the use cases - base64 encoded string where == is pretty usual ending sequence.

**Comment by nzlosh** [comment]
I was able to reproduce the error. It seems the `==` is being interpreted as a key/value pair by the StackStorm API.

The API is returning an HTTP 400 bad request error which err-stackstorm fails to handling correctly.  A PR to fix this issue will be pushed shortly.  The underlying issue of the `==` being interpreted as a key/value pair has not been resolved, but will allow you to open a an issue on the St2 repository.
