### ISSUE TITLE
if "slack" in extra

### ISSUE THREAD

**Issue by minifygb** [nzlosh/err-stackstorm#40]
errbot_1  | 2021-05-28 09:16:26,030 DEBUG    errbot.core               Ignoring message from self.
errbot_1  | 2021-05-28 09:16:26,036 DEBUG    urllib3.connectionpool    https://slack.com:443 "POST /api/chat.postMessage HTTP/1.1" 200 339
errbot_1  | 2021-05-28 09:16:26,038 DEBUG    errbot.flow               Test if the command st2 is a trigger for an inflight flow ...
errbot_1  | 2021-05-28 09:16:26,038 DEBUG    errbot.flow               None matched.
errbot_1  | 2021-05-28 09:16:26,038 DEBUG    errbot.flow               Test if the command st2 is an auto-trigger for any flow ...
errbot_1  | 2021-05-28 09:16:26,149 DEBUG    errbot.backends.slack     No event handler available for desktop_notification, ignoring this event
errbot_1  | 2021-05-28 09:16:29,366 DEBUG    errbot.plugin.st2.st2_api *** Errbot announcement event detected! ***
errbot_1  | event: st2.announcement__errbot
errbot_1  | data: {"payload": {"extra": null, "context": null, "whisper": false, "user": null, "message": "*Failed Licensing execution:* request json data 111", "channel": "@1111"}, "trace_context": null}
errbot_1  |

errbot_1  | 2021-05-28 09:16:30,438 DEBUG    errbot.backends.slack     Escaped IDs event text: _Failed Licensing execution:_ request json data 111 requested by ddddd
errbot_1  | 2021-05-28 09:16:30,439 DEBUG    errbot.core               Ignoring message from self.
errbot_1  | 2021-05-28 09:16:30,442 CRITICAL errbot.plugin.st2.st2_api St2 stream listener - An error occurred: <class 'TypeError'> argument of type 'NoneType' is not iterable.  Backing off 10 seconds.
errbot_1  | Traceback (most recent call last):
errbot_1  |   File "/srv/plugins/err-stackstorm/lib/stackstorm_api.py", line 186, in st2stream_listener
errbot_1  |     listener(callback, bot_identity)
errbot_1  |   File "/srv/plugins/err-stackstorm/lib/stackstorm_api.py", line 176, in listener
errbot_1  |     p.get("extra"),
errbot_1  |   File "/srv/plugins/err-stackstorm/lib/chat_adapters.py", line 331, in post_message
errbot_1  |     if "slack" in extra:
errbot_1  | TypeError: argument of type 'NoneType' is not iterable
errbot_1  | 2021-05-28 09:16:40,458 WARNING  errbot.plugin.st2.st2_api Bot credentials re-authentication required.

I'v made quick fix and it works. please check

--- a/lib/chat_adapters.py
+++ b/lib/chat_adapters.py
@@ -328,7 +328,7 @@ class SlackChatAdapter(GenericChatAdapter):
         else:
             if extra is None or extra == {}:
                 self.bot_plugin.send(target_id, message)
-            if "slack" in extra:
+            if extra and  "slack" in extra:
                 # https://api.slack.com/reference/messaging/attachments#legacy_fields
                 legacy_fields = set([
                     "author_icon",

**Comment by nzlosh** [comment]
Good catch! Can you create a PR for this please?
