### ISSUE TITLE
Did not work with errbot docker

### ISSUE THREAD

**Issue by pvyaka01** [nzlosh/err-stackstorm#43]
Trying this out. I'm not able to install errbot itself, it fails with some setuptools problem. So, used docker image which works fine for errbot.

My env:
1. OS: Red Hat Enterprise Linux Server release 7.9 (Maipo)
2. python3 version: python3 --version
            ****Python 3.6.8****
3. pip3 version: 
**pip 21.3.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)**

However, when I tried installing this plugin, it is throwing some errors. Not well versed in this so trying to see if I'm not doing something right.

It fails with:
Some plugins are generating errors:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/errbot/plugin_manager.py", line 289, in _load_plugins_generic
    plugin_classes = plugin_info.load_plugin_classes(
  File "/usr/local/lib/python3.9/site-packages/errbot/plugin_info.py", line 100, in load_plugin_classes
    spec.loader.exec_module(modu1e)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/errbot/data/plugins/nzlosh/err-stackstorm/st2.py", line 19, in <module>
    from lib.stackstorm_api import StackStormAPI
  File "/home/errbot/data/plugins/nzlosh/err-stackstorm/lib/stackstorm_api.py", line 7, in <module>
    import sseclient
**ModuleNotFoundError: No module named 'sseclient'**

1. I installed latest errbot image with:
docker pull errbotio/errbot:latest (tried 6.1.9 as well)

2. Start with:
docker run -it 436b9019ca56 -c ./config.py

3. Try installing repo:
[@CHANGE_ME ➡ @errbot] >>> **!repos install https://github.com/nzlosh/err-stackstorm.git**
Installing https://github.com/nzlosh/err-stackstorm.git...
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests>=2.20.0 in /usr/local/lib/python3.9/site-packages (from -r /home/errbot/data/plugins/nzlosh/err-stackstorm/requirements.txt (line 1)) (2.27.1)
Collecting sseclient
  Downloading sseclient-0.0.27.tar.gz (7.5 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/site-packages (from requests>=2.20.0->-r /home/errbot/data/plugins/nzlosh/err-stackstorm/requirements.txt (line 1)) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/site-packages (from requests>=2.20.0->-r /home/errbot/data/plugins/nzlosh/err-stackstorm/requirements.txt (line 1)) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/site-packages (from requests>=2.20.0->-r /home/errbot/data/plugins/nzlosh/err-stackstorm/requirements.txt (line 1)) (2022.5.18.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/site-packages (from requests>=2.20.0->-r /home/errbot/data/plugins/nzlosh/err-stackstorm/requirements.txt (line 1)) (1.26.9)
Requirement already satisfied: six in /usr/local/lib/python3.9/site-packages (from sseclient->-r /home/errbot/data/plugins/nzlosh/err-stackstorm/requirements.txt (line 2)) (1.16.0)
Building wheels for collected packages: sseclient
  Building wheel for sseclient (setup.py) ... done
  Created wheel for sseclient: filename=sseclient-0.0.27-py3-none-any.whl size=5584 sha256=f3983832f82d8469375b7afe2fc7439a8af1feff2da64a8c3514401422e34429
  Stored in directory: /home/errbot/.cache/pip/wheels/73/21/3f/9d20c05c1c9312ab61bc7bf63bb2c189a71e800cb028fa8d2a
Successfully built sseclient
Installing collected packages: sseclient
Successfully installed sseclient-0.0.27
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests>=2.20.0 in /usr/local/lib/python3.9/site-packages (from -r /home/errbot/data/plugins/nzlosh/err-stackstorm/requirements.txt (line 1)) (2.27.1)
Requirement already satisfied: sseclient in ./.local/lib/python3.9/site-packages (from -r /home/errbot/data/plugins/nzlosh/err-stackstorm/requirements.txt (line 2)) (0.0.27)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/site-packages (from requests>=2.20.0->-r /home/errbot/data/plugins/nzlosh/err-stackstorm/requirements.txt (line 1)) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/site-packages (from requests>=2.20.0->-r /home/errbot/data/plugins/nzlosh/err-stackstorm/requirements.txt (line 1)) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/site-packages (from requests>=2.20.0->-r /home/errbot/data/plugins/nzlosh/err-stackstorm/requirements.txt (line 1)) (1.26.9)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/site-packages (from requests>=2.20.0->-r /home/errbot/data/plugins/nzlosh/err-stackstorm/requirements.txt (line 1)) (2022.5.18.1)
Requirement already satisfied: six in /usr/local/lib/python3.9/site-packages (from sseclient->-r /home/errbot/data/plugins/nzlosh/err-stackstorm/requirements.txt (line 2)) (1.16.0)
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Some plugins are generating errors:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/errbot/plugin_manager.py", line 289, in _load_plugins_generic
    plugin_classes = plugin_info.load_plugin_classes(
  File "/usr/local/lib/python3.9/site-packages/errbot/plugin_info.py", line 100, in load_plugin_classes
    spec.loader.exec_module(modu1e)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/errbot/data/plugins/nzlosh/err-stackstorm/st2.py", line 19, in <module>
    from lib.stackstorm_api import StackStormAPI
  File "/home/errbot/data/plugins/nzlosh/err-stackstorm/lib/stackstorm_api.py", line 7, in <module>
    import sseclient
ModuleNotFoundError: No module named 'sseclient'
.
Removing /home/errbot/data/plugins/nzlosh/err-stackstorm as it did not load correctly.
Error: St2 failed to activate: 'NoneType' object has no attribute 'is_activated'.
Plugins reloaded.

**Comment by nzlosh** [comment]
Were you able to use the dockfile in this repo to build a working docker image?

**Comment by nzlosh** [comment]
Closing - stale.
