### ISSUE TITLE
errst2lib/enquiry.py: IndentationError: expected an indented block after function definition

### ISSUE THREAD

**Issue by ClemaX** [nzlosh/err-stackstorm#50]
There seems to be an indentation error:
[errst2lib/enquiry.py](
https://github.com/nzlosh/err-stackstorm/blob/451a94b7074d6a0ab5b10045126b17b0cfe4b759/src/err-stackstorm/errst2lib/enquiry.py#L85C5-L90C30)

**Comment by nzlosh** [comment]
Thanks for pointing that out, it should be fixed in `main` now.
