### ISSUE TITLE
Support Slack Blocks

### ISSUE THREAD

**Issue by nzlosh** [nzlosh/err-stackstorm#9]
Add support to the backend chat adapter.  This feature may also require updating errbot's slack backend code.

https://api.slack.com/messaging/attachments-to-blocks

**Comment by nzlosh** [comment]
https://github.com/StackStorm/hubot-stackstorm/issues/166

**Comment by nzlosh** [comment]
https://github.com/errbotio/errbot/issues/1319

**Comment by bloodywing** [comment]
```python
from errbot import BotPlugin
from errbot.backends.base import Identifier
from pprint import pformat

class SlackBlocks(BotPlugin):

    def block(self, to: Identifier, blocks: []):
        self.log.debug('blocks: %s' % pformat(blocks))
        if self._bot.mode == 'slack':
            self._bot.api_call('chat.postMessage', data={
                'channel': to,
                'as_user': True,
                'attachments': [
                    {
                        "blocks": blocks
                    }
                ]
            })
```

I made a plugin which does something like that, it takes the blocks as dictionary. Slack is a bit wonky regarding the blocks and empty strings cause issues. I'll make it a full plugin when I tested this more. The `to` parameter is something like: `self.build_identifier('#mychannel')` When you write your plugin use the SlackBlocks as DependsOn and you can use it in your own Plugin.

The blocks list is what Slack shows you in the blockbuilder on their site.

**Comment by nzlosh** [comment]
@bloodywing Thank you for sharing your implementation. :+1: I finally got around to implementing this and your example was useful.
